# Generated by Django 2.1.3 on 2018-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0002_class_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.IntegerField(),
        ),
    ]
